### ISSUE TITLE
Too much white space between pie chart and "Portfolio" section border on wallet dashboard

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1006]
**Wallet version or commit SHA:**
71bee7e

**Environment:**
Win 10 Home (64 bit) Version 1709 Build 16299.371

**Prerequisites:**
At least one wallet imported to the app

**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Login using a saved wallet" button
3. Select your wallet, enter your passphrase and click on "Login" button

I find it important as fixing this could give us more space for values in "Portfolio" section and do less truncating.

For reference check `2.0-Home-Light` designs.

**Screenshots/Video:**

*Currently*:
![curr](https://user-images.githubusercontent.com/8177587/39123675-d3ce0bc4-46f8-11e8-9488-a963081117bb.png)

*Expected*:
![exp](https://user-images.githubusercontent.com/8177587/39123679-d7564144-46f8-11e8-9327-c7b89d77e3cb.png)

**Comment by drptbl** [comment]
Fixing this issue could create more space for: #1005

**Comment by drptbl** [comment]
@alexhulbert Hmm.. I'm still experiencing issues there.
My resoultion is 1920x1080 if it helps in any way.

**Current look, after fixes:**
![current](https://user-images.githubusercontent.com/8177587/41008913-1c67bf54-692e-11e8-9894-8641a23fad6d.PNG)

**Expected, from designs:**
![expected](https://user-images.githubusercontent.com/8177587/41008915-2012178a-692e-11e8-90dd-d961761ba298.PNG)

**Comment by alexhulbert** [comment]
My resolution is also 1920x1080, but I'm running Ubuntu Linux 16.10. On my machine, The top of the pie chart is flush with the top of the first legend item.

**Comment by alexhulbert** [comment]
It looks like there's an issue with vertical alignment (the horizontal displacement is my fault). This might be because my window manager is letting me resize the window however I want. I can probably fix the issue on both our ends by either vertically top-aligning the pie chart or removing the padding on the inner SVG. The latter would create a bit of hacky CSS. Also, this might not be an issue on windows (since I'm not sure if you can even resize the neon-wallet window on anything other than linux), but as you decrease the width-to-height ratio of the neon wallet window, the window starts to look like this:

![Incorrect Alignment](https://user-images.githubusercontent.com/2229212/41009694-94b43fba-6900-11e8-952a-00b5ca3653ad.png)

Any thoughts on how I should proceed with this issue?

**Comment by drptbl** [comment]
Re-tested, working fine. Thanks ;).
