### ISSUE TITLE
Calculating Claimable Gas Failed Neon version 0.2.4

### ISSUE THREAD

**Issue by lavalleynh** [CityOfZion/neon-wallet#1056]
Consistently fail to Calculate Claimable Gas with all recent versions 0.2.2 - 0.2.4

**Wallet version or commit SHA:**
0.2.4

**Environment:**
Win 10 64

**Prerequisites:**
e.g.: Don't have any custom tokens added before running the wallet

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Use my Ledger Nano S
3. Claim Gas - and fail.... 

some description (for ex. what happens after completing reproduction steps), e.g.:
After clicking on "Add a new token" button, wallet "hangs" for 2 seconds.

**Screenshots/Video:**
e.g.: https://example.com/screenshot.png

**Comment by mhuggins** [comment]
Not enough information.

**Comment by mhuggins** [comment]
Everything in the form that you left blank would be helpful.

**Comment by lavalleynh** [comment]
Provided more information in the original comment.  Any particular questions you have that I can answer?

**Comment by mhuggins** [comment]
Can you share your address?  You can private message me on Discord with it if you prefer.

**Comment by VinceDot** [comment]
Try going to : https://api.neoscan.io/api/main_net/v1/get_balance/{your ledger address} and check how many GAS dust you have (How many inputs appear for 'GAS').

Everytime you claim GAS you create an input with the amount claimed, actually the total you see on NEON wallet is just the addition of every inputs but since the ledger cannot sustain too much inputs at the same time this may be why you are unable to claim GAS.

Try sending to yourself your whole stack of GAS so it will create one input only for that amount of GAS and then try claiming GAS again.
