### ISSUE TITLE
Neo comes and leaves infront of my eyes. I pulled 12 neo out of binance around 13:30 gmt+1 English summer time. If I claim gas it turns back to 34. I log out and log back in again in my nano ledger s and its back. Cant see it actually been confirmed in the history but ran a scan and found it.Is its going to be gone? like the problems in January?  

### ISSUE THREAD

**Issue by sascroft** [CityOfZion/neon-wallet#1105]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
 0.2.4 mac dmg

**Environment:*
![img_4127](https://user-images.githubusercontent.com/39304699/40059476-6ea4eed0-5854-11e8-904a-d2a17d4f3fd4.JPG)
![img_4128](https://user-images.githubusercontent.com/39304699/40059491-778721b2-5854-11e8-909a-34397c821607.JPG)

**Prerequisites:**
e.g.: Don't have any custom tokens added before running the wallet

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Click on "Manage Neon settings" button
3. Click on "Manage Tokens" button
4. Click on "Add a new token" button

some description (for ex. what happens after completing reproduction steps), e.g.:
After clicking on "Add a new token" button, wallet "hangs" for 2 seconds.

**Screenshots/Video:**
e.g.: https://example.com/screenshot.png

**Comment by drptbl** [comment]
This is caused because of current on-going issues with neon-wallet API (`api.neonwallet.com/v2/`) and neoscan API (`api.neoscan.io`) are under DDoS attack.

More details here:
https://www.reddit.com/r/NEO/comments/8jlkmg/neon_lag_there_is_currently_a_ongoing_ddos_attack/

You can check that currently neon-wallet API is ~12500 blocks behind (http://monitor.cityofzion.io/).
After it's fixed, everything will be back to normal.
