### ISSUE TITLE
Transfered NEO from Exchange. Did not receive transaction history for the transfer in my NEON wallet? 

### ISSUE THREAD

**Issue by unb1dden** [CityOfZion/neon-wallet#1111]
Hello. I transferred NEO from an exchange and it successfully transferred to the NEON wallet, however, I am getting no transaction history within the NEON wallet. The transaction window states "no transactions" but i just received my NEO. Any suggestions so i have transaction history on these transfers? I might leave them on the exchange if this is going to be an issue.

Thanks

**Comment by sascroft** [comment]
I have the same issue. I left my last 5 neo on kucoin after having a issue with 12 I sent yesterday from binance.

**Comment by Malcovis** [comment]
I am also having this issue.  seems like it has been consistent since the new update

**Comment by PiiggyBank** [comment]
Same. I claimed GAS but it isn't showing in the transaction history

**Comment by drptbl** [comment]
This is caused because of current on-going issues with neon-wallet API (`api.neonwallet.com/v2/`) and neoscan API (`api.neoscan.io`) are under DDoS attack.

More details here:
https://www.reddit.com/r/NEO/comments/8jlkmg/neon_lag_there_is_currently_a_ongoing_ddos_attack/

You can check that currently neon-wallet API is ~12500 blocks behind (http://monitor.cityofzion.io/).
After it's fixed, everything will be back to normal.
