### ISSUE TITLE
NEON wallet not showing transaction ID and inconsistently shows correct token balances

### ISSUE THREAD

**Issue by pdufur23832** [CityOfZion/neon-wallet#1113]
Wallet version: NEON wallet: v0.2.4 
Environment: macOS High Sierra - v10.13.4  

Prerequisites: Holding NEO, GAS, RPX, and ONT   

Reproduction steps: 
1.  Sent 4 NEO tokens to Coupit.io Token Sale (AeKFYAV2eyveeWCr7prhTuA8TRGaQSSTJU). 
2.  No Transaction ID is showing for the ‘Send’.
3. NEO balance is sometimes showing the correct balance after sending 4 NEO to Coupit, and sometimes the NEO balance is not showing correct balance.
4. ONT and RPX token balances are sometimes showing, and sometimes it is not showing.
5. Receive error when I try to claim accumulated GAS token.

**Comment by PiiggyBank** [comment]
Same. They balance flash in and out. 

Transaction history is not showing anything recent.

**Comment by drptbl** [comment]
This is caused because of current on-going issues with neon-wallet API (`api.neonwallet.com/v2/`) and neoscan API (`api.neoscan.io`). Mostly caused because of DDoS attack:
https://www.reddit.com/r/NEO/comments/8jlkmg/neon_lag_there_is_currently_a_ongoing_ddos_attack/
You can check that currently neon-wallet API is ~12500 blocks behind (http://monitor.cityofzion.io/).
After it's fixed, everything will be back to normal.
