### ISSUE TITLE
Neon/Ledger nano s

### ISSUE THREAD

**Issue by ichunliu** [CityOfZion/neon-wallet#1312]
Every time I tried send ONT tokens to my Binance account or Neotracker wallet using my ledger nano s .....I got an error message:
Transaction failed: Ledger device: UNKNOWN_ERROR (0x6d07)

And then I have delete all the apps and update my firmware from 1.3.1 to 1.4.2 and install neo application back into my ledger nano s...... and now I try to log in neon with my ledger nano s and it shows that USB error no device found and on the ledger itself it says “public key Request Yet”......before I update to firmware 1.4.2 I was using window 7 and I was able to access neon wallet using my nano s but after updates it.....All I get was this public key request yet and usb error no device found........can anyone help please

**Comment by stehaddy** [comment]
I am a newbie trying to find my Neo, but what i have learned up to now may help you, !st Windows 7 wont complete the ledger update it has to be finished on Windows 10 and 2nd i had the same problem with "no device found" to fix this go into your computer settings and select Control panel/ devices and printers, find the Nano S listed and right click on it and choose the "troubleshoot" option, that allowed me to access my Neo wallet with the ledger but i am still having the following problem if anyone can help it would be appreciated,  I have a neon desktop app that i open with my Ledger Nano S and all was working fine, my Neo and Gas were on there i had even claimed more Gas, but since updating the ledger (although i am not sure it is down to this) when i open the Neo wallet It says 0 Neo and 0 Gas but it does show my public key which is the same one as before, and the Neo are showing on that public key when i check on Neo tracker, I have troubleshot the Ledger since updating, can anybody tell me what i am doing wrong? easy answers please as I am old..
Thanks.
Ps: I have other Cryptos on the same Ledger that are all accessible the problem appears to be just with Neo.
