### ISSUE TITLE
Lost $1100 with Neon

### ISSUE THREAD

**Issue by qweqwa** [CityOfZion/neon-wallet#132]
So I downloaded Neon 0.0.3 last week and some hours ago I accidentally deposited 27 NEO to my Bittrex BTC address. The erroneous transaction 'created' a new Neo address which I obviously can not access:
https://neotracker.io/tx/5c632d9dac1d4218ce239f20f977065e8804555765c3e9ff8699174843b5f448

I'm not going to ask if it's possible to get them back, because it's not very likely. I was told that Neon should have prevented me from paying to a wrong type of address, but looks like it didn't. Is this something that 0.0.4 prevents?

Another thing, a moment ago I got a deposit to my NEO address on Bittrex and the txid looks weird to me: NEOWRFND6f061d9e9b50754d2c797a2962afc56cd0e42f01
I've never shared my Bittrex Neo address, so what does this mean exactly?

**Comment by anfn101** [comment]
That NEOWRFND6f061d9e9b50754d2c797a2962afc56cd0e42f01 is Bittrex refunding the Neo they took from users sending more than X Neo + their fee. So if you sent 3.5 Neo, they took 0.1 NEO fee and the other 0.4, since Neo is not divisible in the actual blockchain system. They've returned that 0.4 (in that scenario). As for the prevention, yes, we had some invalid address prevention in 0.0.3, but we've expanded that even more in 0.0.4 and it should have been able to cover this case you mention.

**Comment by qweqwa** [comment]
d

**Comment by qweqwa** [comment]
"It should have been able" well it wasn't. And the Neo dev team didn't even respond to me.
Fuck this dying hypecoin and its devs and wallet devs.

**Comment by comountainclimber** [comment]
Your silly mistakes are not the fault of this project.  These type of comments do not belong on github or in the issues threads
