### ISSUE TITLE
Update design for creation/import in Home container view

### ISSUE THREAD

**Issue by comountainclimber** [CityOfZion/neon-wallet#1338]
https://github.com/CityOfZion/neon-wallet/tree/design-v2/design

**Comment by drptbl** [comment]
@comountainclimber List of issues there (there're many of them, please let me know if you want separate tickets for them):

## Shared issues (for both screens):
1. Unnecessary scroll bar is visible on this page (content is too big for default window size of the wallet)
2. There should be a "cross" button on the right side instead of "back arrow" button on the left

## Creation screen:
![not_in_line](https://user-images.githubusercontent.com/8177587/43745596-f3cabadc-99df-11e8-831b-a847ee06e2a4.PNG)

1. "Create New Wallet" label is not hortizontally centered with "plus inside circle" icon
2. "Create New Wallet" and "Enter Details" labels should be covered with lighter color than the rest of labels (on dark designs they're white and rest of labels are grey). This should be clarified for white designs. This color should also match with color of "cross" button according to designs (which allows you to go back to previous screen).

## Import screen:
![import_wallet](https://user-images.githubusercontent.com/8177587/43746225-3d8271f8-99e3-11e8-9526-3b61a29ace9f.PNG)

1. Wrong icon before "Import Wallet" title (it should be a "cloud with input" instead of "checkmark in circle")
2. "Import Wallet" and "Enter Details" labels should be covered with lighter color than the rest of labels (on dark designs they're white and rest of labels are grey). This should be clarified for white designs. This color should also match with color of "cross" button according to designs (which allows you to go back to previous screen).

**Comment by comountainclimber** [comment]
Fixed in design-v2 branch
