### ISSUE TITLE
Claiming GAS can be buggy (reset one's claim and not award GAS)

### ISSUE THREAD

**Issue by FatCat0** [CityOfZion/neon-wallet#143]
I've encountered two separate bugs re: GAS. I'm hesitant to investigate further (since there's a literal cost associated), but on one occasion I received 0.0000 GAS for a claim that should have been >0, and on two occasions I've just not received a GAS transaction period. I don't know what happened with the former, but with the latter it can be recreated easily: Claim GAS and close the client before the transaction clears. I forget exactly at which step (after the NEO goes through but before the GAS shows up? After it's sent but before the NEO transaction shows up in your history? Before it's even sent?), but it's somewhere in there. Again, hesitant to test it out more at my own expense. The "0.0000 GAS" event might have been related to trying to recreate the "No GAS shows up at all" event, so maybe that happens when quitting at a different point in the transaction.

You can thank Windows Update for my having found this in the first place.

**Comment by canesin** [comment]
Thanks for the report @FatCat0, I will try using testnet so there is no need for you to expend anything.

**Comment by Ejhfast** [comment]
@FatCat0 this is almost certainly a formatting bug and you *did* receive the gas in your account. what does your balance say on neotracker? 

we are working to improve the display of incoming gas in small amounts

**Comment by FatCat0** [comment]
I think you're correct about the ones showing as 0.0000 (checked on neotracker). I have a couple claims that give me the 0 NEO transaction in my wallet but not the GAS transaction (as in no GAS transaction shows up at all), so I can't check them. I'll PM you one such transaction.

**Comment by totalvm** [comment]
@FatCat0 Please reopen this issue if you still have trouble

**Comment by jmachoff** [comment]
I am also getting this issue still. I have unclaimed GAS that doesn't seem to want to appear. Every time I try to claim the GAS it just stays unclaimed and at 0.

**Comment by Ejhfast** [comment]
Thanks, we are looking into it, seems to be an issue for some user
accounts, especially with long history of unclaimed GAS

**Comment by jacobgdinesen** [comment]
I have the same problem. I have never been able to claim gas. I have around 6 unclaimed gas available, but whenever i hit the "claim 6 gas" button it just generates a NEO transaction of 0, with no gas at all. I have had this problem since my first installed version of NEON (think it was 0.0.3) until now, currently at 0.0.7.

**Comment by tofugitive** [comment]
I've got enough unclaimed GAS that the inability to claim them is beginning to become rather uncomfortable. Is a fix on the way? Not sure how many people are affected, but this is obviously a major glitch in the matrix and is good enough reason to completely avoid the Neon wallet.

**Comment by Ejhfast** [comment]
It is affecting very few people so far (which makes it hard to debug!) But
we are working on it, should be fixed soon -- I'd recommend using
neotracker wallet in the meantime if you are affected

**Comment by tofugitive** [comment]
Understood it may be difficult to debug. If I move my NEO to Neotracker, will my unclaimed GAS follow me so that I can claim it there? (Sorry for the newbie question!)

**Comment by Satoshinaire** [comment]
@tofugitive If you move your NEO to neotracker by importing your existing private key, then yes your unclaimed GAS will follow you.

However, if you create a new address on neotracker and transfer your NEO there, no your GAS won't follow, it will stay in the first address. However it should be claimable there once the bug is resolved. Better to import private key into neotracker though.

Hope that helps :)

**Comment by tofugitive** [comment]
@Satoshinaire thanks much! Will wait and see if bug is resolved and if not, will move to Neotracker with private keys.

**Comment by cryptomitchman** [comment]
So just so I understated. I've been trying to claim gas for a month. No luck with 0.0.5, 0.0.6, and now 0.0.7.  If I move some neo to sell to bittrex, but keep my original wallet. Will the gas still be there when the problem is solved - even though I sell my NEO?

**Comment by Ejhfast** [comment]
Yes, unclaimed GAS will still be there

**Comment by cryptomitchman** [comment]
Thanks Ejhfast. Been stressing me out. I appreciate the response. I tried everything from NEON to neo tracker. Just cant claim it. If it helps anyone debug the issues, I originally started my first wallet as a antshares original wallet.

**Comment by cryptomitchman** [comment]
Actually finally worked on Neo Tracker. Had to send to myself first and wait! Finally! Thanks

**Comment by edbaks** [comment]
Trying to claim gas for a long time 0.5 0.6 and 0.7 not working.
Send to my self is also not working.
I ám not the only one, its undermine the credibility of the NEO platform when you not to be able to fix it.

**Comment by Freeminder23** [comment]
Same here....using Neon-Wallet with a Ledger Nano S and when I try to claim it's giving the message:
"Sign transaction 1 of 2 to claim Gas on your hardware device (sending Neo to yourself)" and then shortly later I have a Transaction of 0 Gas in my history. Will have to switch to Neotracker again if this is not fixed soon....

**Comment by subzero788** [comment]
I'm also using Neon with a Nano S and when I try to claim, I sign the transaction on the nano then get a "Transaction Failed!" message from neon

**Comment by jayddaniels** [comment]
i tried several wallets, latsly neo tracker, and still it is unclaimed, i havent tried to claim for about 4 months, now its impossible ?

**Comment by mrz1836** [comment]
My old antshares wallet will not claim at all. I think NEO might have an issue with older antshare wallet addresses. Unless the team can shed light on it, I am unable to claim any GAS from all neo wallets.

**Comment by jayddaniels** [comment]
I could after all claim my gas 2 days later. IT wrote error constantly, for days and then once it claimed, tho I did the same always, just clicked claim in the web wallet.

**Comment by mrz1836** [comment]
+1 to reopen issue or escalate.

**Comment by inancgumus** [comment]
```
Processing
Sign transaction 1 of 2 to claim GAS on your hardware device (sending NEO to yourself)
```

What should I do here?

**Comment by reductionista** [comment]
I'm having a problem claiming gas using Ledger Nano S, but it might be different from the ones listed here.  In my Neon client, the button to claim is just always grayed out with the message "You can claim gas once every 5 minutes" when I hover over.  It's been stuck like that for at least 24 hours.  Possibly got into that state because I forgot to confirm on my Ledger one time, or closed the client too early, not sure.

**Comment by RiccardoF** [comment]
Is there a minimum amount of GAS that is possibile to claim? Because I'm connected with the Ledger Nano S, I try to claim, but I cannot do it, everything seems work fine, but I don't see any transaction in history, the GAS is always 0 and the Gas to claim is still the same as well. Also in the neoscan, I can see that the GAS is unclaimed.
