### ISSUE TITLE
Send  page validation does not validate MAX amount for more 1 recipient

### ISSUE THREAD

**Issue by osmirnov** [CityOfZion/neon-wallet#1665]
**Wallet version or commit SHA:**
2.0.0.dev (be831ac7)

**Environment:**
e.g.: Win 10 Pro (64 bit) Version 10.0.17134 Build 17134

**Prerequisites:**
N/A

**Reproduction steps:**
1. Start Neon Wallet
2. Login
3. Open "Send" page
4. Add the first recipient and 0.01 amount
5. Add the second recipient and 0.01 amount
6. Click MAX button for the first recipient or type the MAX amount in input -> The amount will be exact MAX instead of MAX - 0.01. The "Send" button is active

Expectation: MAX amount validation should validate all amount fields.

**Screenshots/Video:**
![image](https://user-images.githubusercontent.com/454196/48305456-8fc6e880-e4f8-11e8-969c-4e8e2706ffc8.png)

**Comment by comountainclimber** [comment]
Sorry did not mean to close this issue... Good find @osmirnov will add this to the project board for prioritization for 2.0.1

**Comment by ranbena** [comment]
@comountainclimber I looked into this:
The max amount is calculated under the assumption that the NEO amount won't be a fraction so "0.01" is calculated as "0".

Options:
1. Enforce whole numbers on NEO amount input fields.
2. Disable "max" button until amount fields are valid.
3. Calculate amount "0.1" as "1" instead of "0".

Looking at the code though, these won't be easy to implement.
My suggestion is to leave it as is, as it is an edge case and also a validation error will appear on the faulty amount upon submission anyhow.

**Comment by comountainclimber** [comment]
Closing this one for now
