### ISSUE TITLE
Disable "Add" buttons on transaction confirmation page next to addresses which are added to contacts list

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1689]
Also instead of wallet addresses, we should show their names from contact list?

![added](https://user-images.githubusercontent.com/8177587/48379276-dc1a5000-e6d3-11e8-80b2-a67e9f7f1824.PNG)

Correct example from "Activity" page:
![hist](https://user-images.githubusercontent.com/8177587/48379478-90b47180-e6d4-11e8-8627-8a08fc2d966c.PNG)

**Comment by ranbena** [comment]
I've looked into this and here are a few ways to go:
1) Quick and dirty; copy the functionality from `Blockchain/Transaction/Transaction.jsx` to `/SendSuccessTransaction` and `SendPanel/SendSuccess/index.jsx`
2) Mild refactor; integrate `Transaction.jsx` into `SendSuccess`.
3) Complete refactor to `Transaction.jsx` - remove code duplication, make readable, perf optimal,  split to separate components that inherit from `<Transaction>`, proper typing, reusability, cohesive styling across the Activity and Send pages.

* I can live with #1 if you can. There's other stuff to work on.
* Already [done a POC](https://github.com/ranbena/neon-wallet/commit/9ac4693034188f8b85b9705b5f7467ab1749ddb8) with #2 that works but still dirty
* But my tendency is to go with #3 but it might be overkill - the issue is to disable the "add" button...

@comountainclimber and others wdyt?
