### ISSUE TITLE
5 Missing Neo Tokens from Neo Wallet

### ISSUE THREAD

**Issue by tvwalls2** [CityOfZion/neon-wallet#1709]
Thanks in advance! I haven't checked my Neo wallet all year and I am missing all of my tokens and GAS-which is why I decided to check it (to see how much accumulate GAS I had). Was there an update? Is this an error? How do I get my tokens back? I obviously can source and prove the purchase and the date. What do I do? Thanks again!

**Comment by asohbat** [comment]
im pretty much pissed off about this situation . my ledger wont show balances then i cant send anything when the balance shows zero . im stuck with this awful wallet app i dont know who will answer investors during withdrawal emergencies

**Comment by comountainclimber** [comment]
@asohbat your input is completely unnecessary and does not help. @tvwalls2 have you double checked a block explorer to confirm your address actually holds those assets?

**Comment by asohbat** [comment]
my input right as im typing it will help everybody 👍 

just managed to extract my private key from ledger since my address HOLDS THE EXACT AMOUNT IN THE BLOCK EXPLORERS .
then manually put it into neotracker.io and TADA ! withdrew all of it in a bling of an eye to my binance . WILL NEVER EVER USE NEONWALLET ANYMORE
