### ISSUE TITLE
Occasional wallet version check message pops up

### ISSUE THREAD

**Issue by DalderupMaurice** [CityOfZion/neon-wallet#1718]
the 
```
Error checking wallet version! Please make sure you have downloaded the latest version: https://github.com/CityOfZion/neon-wallet/releases
```
Toast is shown, while using the latest version of the wallet

**Wallet version or commit SHA:**
2.0.0

**Environment:**
macOS Mojave 10.14.1 (18B75)

**Prerequisites:**
/

**Reproduction steps:**
e.g.:
It's not very clear HOW this happens.
I tried installing the older version and reinstalling the newest version, but it appears at most of the time when I quit the app and start it back up.

**Screenshots/Video:**
![image](https://user-images.githubusercontent.com/10922045/48906225-161deb80-ee64-11e8-810f-be2e82fe4918.png)

**Comment by ranbena** [comment]
Looking at the code, this error message will pop up due to release version data fetch failure - probably network or API problem. It will appear even for apps that _are_ up to date.

I suggest:
1. Suppressing the error message. The user can't do anything about it anyway.
2. Implementing retry mechanism (perhaps with [axios-retry](https://www.npmjs.com/package/axios-retry))
3. Considering remote error logging to monitor and get insight on errors more easily.

@comountainclimber wdyt?

**Comment by comountainclimber** [comment]
@ranbena I am on board with with #1 and #2 seeing as we currently have no remote error logging monitoring service in place lets hold off on #3 for now 👍

**Comment by ranbena** [comment]
Cool I'm on it

**Comment by drptbl** [comment]
Implemented retry method works properly. It won't fix the issue completely, but for sure it will make it less visible (happen more rarely).
