### ISSUE TITLE
[feature] Support to neo-cli UTXO and Claims tracking from new plugin

### ISSUE THREAD

**Issue by vncoelho** [CityOfZion/neon-wallet#1815]
Hi @comountainclimber, maa friend.
Good time in the DevCon, a great pleasure to meet you it was.
Congratulations for the great outstanding work you are all doing here.

With PR https://github.com/neo-project/neo-plugins/pull/52, we gonna be able to query UTXO and Claims direct from a neo-cli node.

I think it is good to have this feature on Neon-Wallet for a better experience.
Probably some nodes will soon add this plugin and enable this query.
Thus, I think that this issue is good to communicate this possibility and prepare the ground for that.

@snowypowers is already adjusting neonjs for handling that as well, as an API.Provider: https://github.com/CityOfZion/neon-js/issues/395

There is also NEP5Tracker plugin now (I still need to test it more deeply), which may be another good api for tracking NEP5 balance: https://github.com/neo-project/neo-plugins/tree/master/RpcNep5Tracker

**Comment by comountainclimber** [comment]
@vncoelho It was a pleasure/great time meeting you out Seattle! Was very impressed by the NEO research team booth and panel discussions!

Sorry for the delay in getting back to you - being able to query for UTXO and claim information from a neo-cli node would be a huge win for us as we could use the node directly for this info instead of relying on neoscan. Thank you so much for bringing this to my attention - I will keep an eye on CityOfZion/neon-js#395 👍 👍
