### ISSUE TITLE
feature suggestion: wallet in "view only" mode for any address

### ISSUE THREAD

**Issue by comountainclimber** [CityOfZion/neon-wallet#1827]
Adding a new feature to the authentication process which would allow a user to "view" any wallet on the network. Tabs like 'Send' and 'Token Sale' would be disabled in this state. Any other suggestions and ideas should be discussed here.

**Comment by phetter** [comment]
1. Watch Feature: I'd like to add a tab called "Watch"  under either "Receive" or "Contacts" that is a list of wallets and a concise overview of their holdings. A drill down would show full detail of holdings, last transaction time, link to all transactions on a third-party explorer, and offer more options such as "add to contacts", "remove watch", activity email alerts, etc.

2. "Contacts" page should have a button like "add to watch".

3. "Add Watch Wallet" button should be on "Watch" page that pops up a modal to add a new watch wallet the list.

4. View Feature: "Watch" page list view (if there is room) and/or detail view should have a button that takes you to a "Wallet" tab view for that particular address to satisify the original request of this feature suggestion. This page instead of saying "My Public Address:" at the top left should say "Watching Address:" or "Viewing Address:".

4.a. An "Watch Wallet" Activity page could be available from here too, but I don't feel it is necessary at this point as the address on the new "View Wallet" links to a list of transactions on Neoscan Explorer. I'm open to adding a "Watch Wallet Activity" version of the main "Activity" tab however.
