### ISSUE TITLE
Travala.com AVA Price not displaying

### ISSUE THREAD

**Issue by warwickchapman** [CityOfZion/neon-wallet#1889]
**Wallet version or commit SHA:**
2.2.1

**Environment:**
MacOS 10.14.5 (18F132)

**Prerequisites:**
None

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Click on "Wallet" button
3. In "Token Balances" section, AVA is listed with "N/A" in price

AVA price information is readily available and has been for over 12 months: https://coinmarketcap.com/currencies/travala/

**Screenshots/Video:**
![image](https://user-images.githubusercontent.com/6004561/60754518-66f0e780-9fe2-11e9-8cd3-a4edede7e4af.png)

**Comment by hal0x2328** [comment]
Apparently AVA is listed as "AVALA" on CryptoCompare, which is the API Neon uses to get pricing data, so the pricing data request for `AVA` returns no data. (They have a defunct ERC-20 token listed using the AVA symbol).

There may be other silent token symbol changes preventing other token prices from displaying, someone should do an audit and figure out how to add special handling to Neon to deal with CryptoCompare's renaming instances.

Rather than hard-coding substitutions in the Neon code, maybe it would be good to have an optional field such as `cryptocompareSymbol` added to the token objects in the tokenList.json file, then if it was present, the pricing request code could default to use that value instead of that of `symbol` so we can easily fix these edge cases going forward.

**Comment by comountainclimber** [comment]
Thanks for reporting @warwickchapman we will get this fixed

**Comment by dauTT** [comment]
FYI, I am working on this.

**Comment by comountainclimber** [comment]
Awesome @dauTT 💪 💪 

Just so you know an example of this already exists for SOUL as you can see in `pricesActions.js` https://github.com/CityOfZion/neon-wallet/blob/dev/app/actions/pricesActions.js#L10 I am ok with using this solution as a temporary work around until we can implement what @hal0x2328 was discussing

**Comment by dauTT** [comment]
Thanks for advice! :+1:

**Comment by tmlee** [comment]
Have you considered the CoinGecko open API at https://www.coingecko.com/en/api ?

Price info can be obtained from 
https://api.coingecko.com/api/v3/simple/price?ids=concierge-io&vs_currencies=usd,aud
It looks like id is different, may be due to a rebrand as list can be pulled over at https://api.coingecko.com/api/v3/coins/list

There is a support for contract address but it looks like its only for Ethereum at the moment, for example BAT, https://api.coingecko.com/api/v3/simple/token_price/ethereum?contract_addresses=0x0d8775f648430679a709e98d2b0cb6250d2887ef&vs_currencies=usd%2Ceur

**Comment by dauTT** [comment]
Thanks, @tmlee for the advice. But let see first if we can keep the existing setup by making a small adjustment before switching to a different service provider. :smile:

**Comment by dauTT** [comment]
@comountainclimber ,

I was testing the solution proposed by @hal0x2328, but I realize that www.cryptocompare.com does not track all the nep5 token. For instance, I can't find  `NEX`:

![image](https://user-images.githubusercontent.com/30392990/61904456-2de3cd00-af27-11e9-98c2-c104f2f87bf1.png)
Do I search in right place?

**Comment by comountainclimber** [comment]
I see it here https://www.cryptocompare.com/coins/nex/overview but not sure what the symbol is within their API

**Comment by dauTT** [comment]
Thanks, @comountainclimber. Let see if I can find the api symbol for NEX...

**Comment by dauTT** [comment]
Actually the NEX symbol does exist on the cryptocompare webpage:

![image](https://user-images.githubusercontent.com/30392990/61955555-92506c00-afbb-11e9-9222-a4cbde006866.png)

But we don't get any price via the api call:

https://min-api.cryptocompare.com/data/pricemultifull?fsyms=NEX&tsyms=USD

![image](https://user-images.githubusercontent.com/30392990/61955783-0b4fc380-afbc-11e9-82e4-54f35494f6ee.png)

I have raised a support request to cryptocompare to see how we can solve this issue.

**Comment by dauTT** [comment]
I got the reply from CryptoCompare:

>  Hello,
> 
> Thank you for contacting CryptoCompare.
> We don't have any NEX/USD pairs listed on our website and that is why you can get any price data for that pair. Please use https://min-api.cryptocompare.com/data/price?fsym=NEX&tsyms=NEO since we have NEX/NEO price data available.
> 
> If there is anything else we can do for you, please let us know.
> 
> Best regards,
> CryptoCompare team

So we will need to adjust the api call to accomodate these cases as well and do a crypto fx conversion. :sweat_smile:

**Comment by dauTT** [comment]
@comountainclimber ,

What is the difference between ticker and token column? Can we just keep ticker column and drop the token one?

![image](https://user-images.githubusercontent.com/30392990/61985366-2eed2b00-b009-11e9-808b-e8e259c03f88.png)

**Comment by comountainclimber** [comment]
Closing this as the fix has been merged into `dev` 🎉  - will be in the next release.

**Comment by warwickchapman** [comment]
Thanks team!
