### ISSUE TITLE
Need help finding login to Neon wallet

### ISSUE THREAD

**Issue by NormaAlice** [CityOfZion/neon-wallet#189]
I just started my Neon Wallet.  Got passphrase, public address, private key and encrypted key.  All went well.  Now I can find the link or webpage for the Neon Wallet.  

thanks, I'm a newbie.

**Comment by Satoshinaire** [comment]
Hello @NormaAlice, this is really a question for the #support channel in [Slack](http://neosmarteconomy.herokuapp.com/). GitHub is intended for tracking development tasks, rather than general support.

Having said that, you can download the latest version of Neon here: https://github.com/CityOfZion/neon-wallet/releases
