### ISSUE TITLE
Error when sending tokens from a balance with more than 16 significant digits

### ISSUE THREAD

**Issue by hal0x2328** [CityOfZion/neon-wallet#1899]
**Wallet version or commit SHA:**
2.3.0

**Environment:**
OSX Mojave

**Prerequisites:**
Have greater than 10 million NEP-5 tokens with a 8-digit fraction (e.g. 10000000.00000001)

**Reproduction steps:**
1. Start Neon Wallet
2. Try to send any amount of the tokens where you have >10M in the wallet

Nothing happens in the GUI but the console log shows:
```
Uncaught (in promise) Error: gt() number type has more than 15 significant digits: 247716140.63257673
    at $ (file:///Applications/Neon.app/Contents/Resources/app.asar/app/dist/bundle.js:26:85512)
    at new I (file:///Applications/Neon.app/Contents/Resources/app.asar/app/dist/bundle.js:26:83742)
    at I.Y.greaterThan.Y.gt (file:///Applications/Neon.app/Contents/Resources/app.asar/app/dist/bundle.js:26:91729)
    at t.validateTransactionBeforeSending (file:///Applications/Neon.app/Contents/Resources/app.asar/app/dist/bundle.js:21:9886)
    at n (file:///Applications/Neon.app/Contents/Resources/app.asar/app/dist/bundle.js:21:10163)
    at Array.find (native)
    at t.validateTransactionsBeforeSending (file:///Applications/Neon.app/Contents/Resources/app.asar/app/dist/bundle.js:21:10175)
    at file:///Applications/Neon.app/Contents/Resources/app.asar/app/dist/bundle.js:55:232528
    at p (file:///Applications/Neon.app/Contents/Resources/app.asar/app/dist/bundle.js:66:57807)
    at Generator._invoke (file:///Applications/Neon.app/Contents/Resources/app.asar/app/dist/bundle.js:66:57595)
```

**Comment by dauTT** [comment]
Thank you @hal0x2328  for reporting! I will have a look at this issue.

**Comment by dauTT** [comment]
@hal0x2328 ,


On Ubuntu, I did a transaction on test and didn't find have any problem the first time:

https://neoscan-testnet.io/transaction/F4B35EB82E2842E3122752D5726F6B33358DD527E024B30E9C8EB290E14F8249

![image](https://user-images.githubusercontent.com/30392990/62413784-551b5800-b613-11e9-8c6b-5ca40ea24567.png)

The second time, when I did the same transaction in the opposite direction I can't:

![image](https://user-images.githubusercontent.com/30392990/62413898-07075400-b615-11e9-805a-bcc3350e1f46.png)

Very strange behavior!!! :confused: . I need to investigate more ...

**Comment by dauTT** [comment]
The error happens exactly at this point:

https://github.com/CityOfZion/neon-wallet/blob/master/app/core/wallet.js#L73

```Typescrypt
if (toBigNumber(amount).gt(balance)) {
    return `You do not have enough ${symbol} to send.`
  }
```

Both `amount` and `balance` are of type number and same value, 100000000.00000001.

Currently we are using bignumber.js version 5.0.0, and this version has the limitation that we can not create a bignumber object from a number which has more than 15 significative digits:

So this is not allowed with version 5.0.0:

```Typescript
const  value = 10000000.00000001
const bn = new BigNumber(value)

=> BigNumber Error: new BigNumber() number type has more than 15 significant digits: 10000000.00000001

```

**The above limitation is removed either by using bignumber.js version 9.0.0 or the  workaround method `toBigNumber` :**

https://github.com/CityOfZion/neon-wallet/blob/master/app/core/math.js#L10
```Typescript

// https://github.com/MikeMcl/bignumber.js/issues/11
export const toBigNumber = (value: number | string) =>
  new BigNumber(String(value))
```

So there are two option to fix this issue:
- **OPTION 1**: Replace the troublesome code with this one:
```Typescript
if (toBigNumber(amount).gt(toBigNumber(balance))) {
    return `You do not have enough ${symbol} to send.`
  }
```
- **OPTION 2**: Simply update bignumber.js version 9.0.0:
This option is a little bit risky because we will need to ensure backword compatibility.

**Comment by dauTT** [comment]
I will create a PR with option1 as it has the less impact possible on the code.
