### ISSUE TITLE
Sending ONT into NEON wallet, transaction on the blockchain confirmed but ONT balance unchanged.

### ISSUE THREAD

**Issue by wick55** [CityOfZion/neon-wallet#2040]
Sending ONT into NEON wallet, transaction on the blockchain confirmed but ONT balance unchanged.

https://explorer.ont.io/transaction/3185581bd8e223e24c3490845ddc97e09721da20c871bebd344547de0d85a0c6

Confirmation on the blockchain.
ONT balance in NEON wallet unchanged.

**Comment by noodles714** [comment]
@wick55 Funny thing that it happened to me to and there wasn't much out there for info.  Previous posters said to join discord but that was of no help.  

What you need to do is create an O Wallet, take your neon private key and input it into the O Wallet and it will appear there.  The O Wallet is the same as Neon but for ONT.   You can claim gas and/or stake your ONT if you have over 500 for a higher return.  Good luck.  I made this account just to help you because we went thru the same thing and couldnt get the right answers outside of an old reddit post a few years ago, thank god it still worked.

**Comment by wick55** [comment]
Thank you ill check it out. I appreciate the post :)
