### ISSUE TITLE
Designs for the UTXO buildup workflow

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/neon-wallet#2090]
This issue covers the designs for the Ledger gas claim workaround when a user has UTXO buildup.

**Comment by hal0x2328** [comment]
A Discord user encountered this today - he has quite a bit of GAS to claim but the transaction is too large for the Ledger to sign. I mentioned https://srp.splyse.tech/ledgerclaim/ as a possible workaround but he is understandably reticent to use it with that much money at stake.

To alleviate this problem, Neon should limit claim transactions to the largest 20 or so UTXOs when it detects a Ledger login. I think this may require modifications to neon-js however since I think the claim transaction builder code may actually be encapsulated there.

If we just do this transparently and only show the user the amount claimable in 20 UTXOs, it should be easy to implement from a UI standpoint, but may be confusing if they see their claimable GAS amount go down after the feature update, or if they compare it to the amount shown in another wallet of Neoscan. But this may not be a significant issue since we are in a migration phase anyway.

Otherwise we'd need to include messaging describing that they are only able to claim a maximum of N of M GAS owed at the current time. But that also could be confusing and require additional explanation anyway.
