### ISSUE TITLE
[wallet connect] - ability to view a list of currently connected dapps

### ISSUE THREAD

**Issue by comountainclimber** [CityOfZion/neon-wallet#2135]
**Summary** 
As a user of neon and wallet connect, I can see a list of all the currently connected dapps to my wallet on the dashboard.

**Designs:**
https://tools.avocode.com/comment/groups/f4aeb93f05d34ff79bcd8c094e302b2c?artboardOriginalId=5A098DC3-BCAA-4CF2-A65A-E77B9F580650&theme=light

**Acceptance criteria:** 

In the Wallet page, users should see a new button at the top right corner, called dApps:
-  If there are no dApps already connected to the wallet, then no number should apppear at the right side of the button. Also, in this case, if they click on the button the Connected dApps pop up should appear, with no dapps appearing, only the notifications (bell icon) and connect new dapp (+ icon) should appear.
- If there are dApps connected to the wallet, then the button dApps should display how many are connected and when clicking on it, the pop up will display the dApp icon, name and the button to Disconnect.
 - Users should be able to disconnect the dApp from the wallet, subsequently removing it from the list.

**Comment by melanke** [comment]
A few more information about this issue that might be interesting:

- Coz already have a React Wallet App that has all features related to Wallet Connect to be used as reference. The main branch is fine, but I am linking this [not-merged branch](https://github.com/CityOfZion/web-wallet/tree/wcsdk) because I've separated the WC logic from other things on it. It uses a copy of a near future WcSdk for wallets, so for now will need to have WalletConnectContext file on the wallet but in the future you will be able to import it as dependency. Check this wallet branch to understand how to implement it on Neon Wallet Desktop. I suggest to run this wallet app on your machine and also run [crypsydra](https://github.com/east-side-cryps/crypsydra-web) to be able to test the connection. Checkout this Gif of both interacting with each other:

![gif](https://github.com/CityOfZion/wallet-connect-sdk/raw/WCS-5/demo.gif)

- For this issue to be considered completed the user will be able to:
  - Connect to a new dapp (like crypsydra) by using the QRCode interaction and viewing the dapp details before accepting the connection
  - View this dapp on the list of connected dapps
  - Be able to remove the connection with the dapp

- **Not** necessary for this issue:
  - Show or Accept requests from the dapp
