### ISSUE TITLE
Collapse UTXO prior to migration if long

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/neon-wallet#2181]
In the situation where a user has built up a long UTXO chain (typically due to excessive claims), they will run into the following possible issues during migration:
1. Inability to sign transactions on ledger nano S due to hardware memory limitations
2. Inability to invoke the migration smart contract with a transaction fee below the 10 GAS subsidy.

This issue will be used to discuss an implementation path to mitigate the problem for users. @hal0x2328 has some experience in predicting the issue which may come in handy. We can consider the following mitigation approaches:

1. Passive Information (tweet, guide, or other public communication)
2. Active information (check in-app if this will be encountered and propose a mitigation or reroute the users workflow)

For the actual mitigation, the most deterministic implementation is to have the user send their assets to themselves to collapse the UTXO chain prior to migration. In the case of the ledger problem, this may need to be done over multiple transactions.

And alternative approach is to allow users to attach GAS to their migration transactions. This will also mitigate the issue, but the amount will be variable. This approach will not mitigate the ledger scenario.

**Comment by superboyiii** [comment]
1. sign transactions on ledger nano S due to hardware memory limitations

**Comment by superboyiii** [comment]
1. sign transactions on ledger nano S due to hardware memory limitations

**Comment by superboyiii** [comment]
Issue:
1. Sign transactions on ledger nano S due to hardware memory limitations
2. 1KB free transaction size limit for networkfee, additional length additional payment(tx.size > 1024, 0.001 per byte)
3. Max tx size limit: even some one would like to pay for additional size, he can't make a tx over 100KB.

Solution:
1. Not much amount: try make txs with a little UTXO input (no more than 10 input in 1 tx). Need neon wallet to control input amout. Too much amount: contact NF.
2. Make a UTXO combine tool internal, invoke this tool and auto combine UTXOs with multi Txs. Need some time, may make network crowded at that time.
3. The same to the above.

**Comment by lllwvlvwlll** [comment]
The selected mitigation for this issue is informational if the migration address has UTXO buildup present.  This has been implemented in v2.8.0.
