### ISSUE TITLE
Wallet Connect Governance Integration

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/neon-wallet#2217]
This feature is a tracker for integration of Wallet Connect with the Neo N3 governance portal for aligned release with Wallet Connect support in the aero and neon desktop wallets.

**Comment by melanke** [comment]
Alright, as we talked on the meeting today, I am waiting access to the repository:
https://github.com/neo-ngd/governance-web

**Comment by melanke** [comment]
Just to document so I know what to do when I get back to this issue:

walletconnect library (not WcSdk) is not working with governance-web, there was 2 problems and I managed to fix one of them, the other was mentioned by Joe but his solution didn't work.

More details:
- Since it was not working I dropped WcSdk so I could test using walletconnect library directly to it, and the problem persisted
- It was saying "No matching export (...)" and after some research I found out that I needed to change the imports from `@walletconnect/client` to `@walletconnect/client/dist/cjs`; and from `@walletconnect/utils` to `@walletconnect/utils/dist/cjs/error`. Ok, first problem solved, maybe I need to change this on the WcSdk.
- But then, another problem showed up: "global is not defined", this is a problem that happened to another dev using Angular, Joe solved it by putting `(window as any).global = window` on `src/polyfills.ts`. But I think this file is something related to Angular config, so instead, I've tried putting it on `main.js`, before everything (since I didn't find any solution for Vue/Vite).
- It didn't work, well, I've checked and the global variable was there, inside `window`, but the same error persisted.

Conclusion:
This is a problem on the relationship between walletconnect library and governance-web, it's not related to WcSdk, I couldn't fix it just yet and I could use some hand...

**Comment by melanke** [comment]
Discussion needed:
The governance dapp, dAPI, NeoLine and O3 works differently from how aero works (and consequently how I tought would be implemented on Neon)
Teorically the governance dapp works with testnet and mainnet, it only depends on which network the wallet is connected to.
The wallet says to the dapp which is the network that was chosen by the user
On WalletConnect example is different: the wallet declares that it can work with testnet, mainnet, etc and the dapp that says with which network it wants to connect. (edited) 
And actually, on dapi the wallet also says if its connected to NeoLegacy or N3

**Comment by melanke** [comment]
Last conclusion:
1) have a way for the dapp to specify which network it wants when connecting with the wallet (can be multiple; this is important to not waste time of the user)
2) have a way for the wallet to tell which network was chosen (this is important because the dapp might want to check rpcserver or dora and needs to know which network to use)
3) on every transaction the dapp says on which network to execute (Tyler's idea, it makes sense because sometimes the same account might be used on different networks and the wallet has a global control of which network it is using)
4) if the wallet can't handle that transaction on that network it automatically rejects

Number 2 will be implemented in the future, for now, we are going to check the governance dapp url to understand if the dapp wants to connect with testnet or mainnet
