### ISSUE TITLE
Enhancements to Activity tab to communicate all transaction events

### ISSUE THREAD

**Issue by picarodias** [CityOfZion/neon-wallet#2256]
## Briefing

- We need to be able display Invocation Transactions in the activity list
- Currently the endpoint from Dora only returns NEP-17 Transfer Transactions

## What is to be done?

- We need an endpoint that returns **all transactions**, and a way to easily differentiate `transfer` and `invocation` ones.

**team suggestion:** create a new endpoint so we don't need to change the existing one, preserving backward compatibility.

**Comment by lllwvlvwlll** [comment]
This issue will enhance the activity tab to get formatting cues using a new key `transaction_type` in the `get_address_abstracts` response payload. If the `transaction_type` === `nep17_transfer`, render as currently implemented; otherwise, display a placeholder row which can link to the transaction details page in dora for the relevant txid:

![image](https://user-images.githubusercontent.com/29798928/133667224-1e52690c-f45d-4f5d-b500-907c30035c20.png)

@J-G-W to provide design guidance

**Comment by lllwvlvwlll** [comment]
link to avocode:
https://app.avocode.com/view/b3f452f8deff465e9feb1eedbde6ce41/_/inspect

**Comment by lllwvlvwlll** [comment]
resolved by #2304
