### ISSUE TITLE
failed to claim gas

### ISSUE THREAD

**Issue by ioannistsil** [CityOfZion/neon-wallet#2260]
![image](https://user-images.githubusercontent.com/18231967/133961245-790eed98-379c-4bcb-b329-8e621a7d3574.png)

**Comment by hal0x2328** [comment]
I believe this is because `app/actions/claimsActions.js` is using `getMaxClaimAmountFrom` with the Neoscan API provider instead of the NeoCli provider in neon-js. Neoscan has stopped reporting accurate claim information since block 8M, so we should be relying only on the NeoCli provider for any claim information now.

**Comment by lllwvlvwlll** [comment]
https://github.com/CityOfZion/neon-js/blob/master/packages/neon-api/src/provider/neoCli/core.ts#L63

**Comment by mxdkc** [comment]
Have the same issue and cant find any solution or helpful information. Also no place to ask, as Reddit is not accepting any new posts about it. So, is there any possibility for a regular user right now to claim gas?

**Comment by lllwvlvwlll** [comment]
@mxdkc we will be pushing a hotfix to resolve the issue.

**Comment by mxdkc** [comment]
@lllwvlvwlll I have heared that the possibility for GAS claiming will end mid September. Is this true?!

**Comment by mxdkc** [comment]
Its working now. You can close the topic
