### ISSUE TITLE
Give warning when API is down or wallet lacks connectivity

### ISSUE THREAD

**Issue by Ejhfast** [CityOfZion/neon-wallet#265]

**Comment by evgenyboxer** [comment]
On it

**Comment by skeller88** [comment]
In the slack support channel, I read that when the wallet is unexpectedly showing zero balances, it's due to an API connectivity issue. So adding this feature would have the added bonus of cutting down on questions from people about where their NEO funds are.

**Comment by Satoshinaire** [comment]
Yeah, absolutely. I think this actually ties in with #9 as well regarding persistent state (perhaps there should be an issue specifically about persistent state that both of these issues relate to).

It'd be good to keep the balance cached locally so that the 0 doesn't freak people out, even when updated balances can't be obtained due to API outage or network connectivity.
