### ISSUE TITLE
No balance and transaction history in Neon Wallet

### ISSUE THREAD

**Issue by smmujahid** [CityOfZion/neon-wallet#267]
Logged in to my Neon wallet and dont find my balance and transaction hsitory. Why is it so. Where is my balance.

**Comment by smmujahid** [comment]
My all keys are extremely secure and encrypted

**Comment by Sharonth** [comment]
I'm having the same problem!

**Comment by noodles12** [comment]
im having same probs . just went to look at my balance to claim my gas .. and nothing in there

**Comment by smmujahid** [comment]
Is there any technical person from NEON who would respond to our problem?

**Comment by noodles12** [comment]
i dont know .

**Comment by sam05092** [comment]
same problem

**Comment by skwaugh** [comment]
Same issue.  Occurring using both saved address and private keys on both 0.5 and 0.6

Looks like the City of Zion's API is down - 503 errors on everything.
![image](https://user-images.githubusercontent.com/4550411/31861876-c2988658-b702-11e7-856a-705e3319489e.png)

**Comment by VicXNg** [comment]
Yeah same problem here. Was fine about 20min ago

**Comment by skwaugh** [comment]
For the other guys with this issue - there is nothing wrong w/ the wallet or your funds 🙏🏼 .  Something broke on their backend (probably the API that grabs the price from Bittrex or whatever).

**Comment by noodles12** [comment]
i hope its that , im panicking a little lol

**Comment by noodles12** [comment]
i thought i been hacked lol

**Comment by smmujahid** [comment]
But that shows their vulnerability. Its bad.

**Comment by noodles12** [comment]
very true im still new to this crypto and you hear of accounts and wallets being hacked regular.
it aint good

**Comment by skwaugh** [comment]
Completely different.  Doesn't show the vulnerability at all.
Also, this is alpha software - note the 0.x release.  As such, you're agreeing to using software that is NOT guaranteed to be bug free.  If you're concerned with the security wallet, you should not use it.

**Comment by smmujahid** [comment]
is better to shift to binance????

**Comment by s5d2d6** [comment]
I believe Binance is located in China and with what is happening with China and crypto exchanges, I'd be leary

**Comment by counter44** [comment]
My NEON wallet is also empty as of this morning

**Comment by Victor118** [comment]
The same here.
Funds still safe, just take a look at the chain explorer with your public address  to be sure: 
https://neotracker.io/

**Comment by counter44** [comment]
Thx Victor118
that provides some peace of mind until they fix this.

**Comment by Pronblra777** [comment]
Всем привет!
Только зарегистрировал кошелек NEON и перевел туда 5 neo, с биржи списали, а на кошельке их нет, прошло часа 2 уже... Помогите, что делать???

**Comment by dkliman** [comment]
same problem. a reddit from a few months ago said neo has a wallet balance server or something that could be down... but if that's the case, then instead of the app scaring the living crap out of people with a zero balance, it should report the server is down, and guide people to see that their wallet is perfectly fine if they look at https://neotracker.io, which is where I went to see my balance is intact.

but first, I nearly had a heart attack. that's not very user-friendly, guys.

**Comment by dkliman** [comment]
it makes me feel awfully uncomfortable for the neon wallet to go to a single server like this... how are my keys kept secure in transit to that? what if it's hijacked?

**Comment by Ejhfast** [comment]
All -- no keys ever touch the database! No keys *ever* leave your machine. The DB just retrieves public balance data. 

Our DB maintainer has been having problems lately. We pay thousands of dollars each month for this, so are looking into better solutions. In the meantime, we are going to pay them even more money so that they go down less often.

We are adding a notification to the wallet in the next release so that you will know when the DB is offline.

Fix to current problem is incoming, should be back up very shortly.

**Comment by dkliman** [comment]
Can't that database be maintained in a dApp, distributed on neo's virtual machine, immune from the vagaries (expense, down time) of old fashioned server companies?

**Comment by Ejhfast** [comment]
NEO / GAS balances do not live on the NEO VM, so short answer is: No

**Comment by Honestbui** [comment]
the same my problem..but how to see for now..pls help
