### ISSUE TITLE
Invalid channel after Ledger OS upgrade

### ISSUE THREAD

**Issue by MDhondt** [CityOfZion/neon-wallet#2733]
**Wallet version or commit SHA:**
2.23.13

**Environment:**
Win 10 Pro (64 bit) Version 22H2 Build 19045.4412

**Prerequisites:**
All working fine with Ledger Nano S (OS 2.0.0)

**Reproduction steps:**
1. Start Ledger Live
2. Update OS from 2.0.0 to 2.1.0
3. OS upgrade successful (other apps are still working fine)
4. Open Neon, login (on N3) with ledger. See overview of all assets
5. Can't do any transactions (claim GAS, send NEO, ...)
5.1 Click Claim GAS; approve via ledger; Neon shows "Error claiming GAS please try again."
5.2 Send NEO; approve via ledger; Neon shows "OOPS! SOMETHING WENT WRONG... Error: Invalid channel"

**Solution attemps:**
- Restarted PC, reconnected Ledger, reinstalled Neon, ...
- Uninstalled and reinstalled N3 app through Ledger Live

**Comment by 0Rudy0** [comment]
I have the same issue but with sending GAS. I managed to send NEO to the exchange but when I try to send GAS it gives me the same error ("Invalid channel"). I have 0 NEO left, only GAS in my wallet, not sure if that makes any difference.

**Comment by Gitvirhub** [comment]
I have been looking for a solution to the problem for several days and I managed to transfer NEO and GAS. 
It looks like the problem is in the NEO N3 Version 0.3.3 ledger application. You need to install NEO N3 
Version 0.1.3. To do this, set the value of My Ledger provider to "12".
![1](https://github.com/CityOfZion/neon-wallet/assets/171830450/7e27228b-a86a-446c-afab-4c547840830d)
![2](https://github.com/CityOfZion/neon-wallet/assets/171830450/e4841d53-9dfe-4598-a238-e6a2a0f77353)

**Comment by qhimself** [comment]
I had registered for notifications on this issue and received an email. I have no idea who the author of the mail was ?!? In any case... Thank you very much. The suggested solution was helpful. I was able to send NEO and GAS.
As other users probably have the same problem, I am copying the suggested solution below. I hope I am not infringing any copyrights ?
---------
I have been looking for a solution to the problem for several days and I managed to transfer NEO and GAS.
It looks like the problem is in the NEO N3 Version 0.3.3 ledger application. You need to install NEO N3 Version 0.1.3. To do this, set the value of My Ledger provider to "12".
[1.JPG (view on web)](https://github.com/CityOfZion/neon-wallet/assets/171830450/7e27228b-a86a-446c-afab-4c547840830d)
[2.JPG (view on web)](https://github.com/CityOfZion/neon-wallet/assets/171830450/e4841d53-9dfe-4598-a238-e6a2a0f77353)

**Comment by Gitvirhub** [comment]
> ## I had registered for notifications on this issue and received an email. I have no idea who the author of the mail was ?!? In any case... Thank you very much. The suggested solution was helpful. I was able to send NEO and GAS.
> As other users probably have the same problem, I am copying the suggested solution below. I hope I am not infringing any copyrights ?
> I have been looking for a solution to the problem for several days and I managed to transfer NEO and GAS. It looks like the problem is in the NEO N3 Version 0.3.3 ledger application. You need to install NEO N3 Version 0.1.3. To do this, set the value of My Ledger provider to "12". [1.JPG (view on web)](https://github.com/CityOfZion/neon-wallet/assets/171830450/7e27228b-a86a-446c-afab-4c547840830d) [2.JPG (view on web)](https://github.com/CityOfZion/neon-wallet/assets/171830450/e4841d53-9dfe-4598-a238-e6a2a0f77353)

Good. Let it help other users.

**Comment by Gitvirhub** [comment]
Good. Let it help other users. 06.06.2024, 11:52, "qhimself" ***@***.***>: I had registered for notifications on this issue and received an email. I have no idea who the author of the mail was ?!? In any case... Thank you very much. The suggested solution was helpful. I was able to send NEO and GAS.As other users probably have the same problem, I am copying the suggested solution below. I hope I am not infringing any copyrights ?I have been looking for a solution to the problem for several days and I managed to transfer NEO and GAS.It looks like the problem is in the NEO N3 Version 0.3.3 ledger application. You need to install NEO N3 Version 0.1.3. To do this, set the value of My Ledger provider to "12".1.JPG (view on web)2.JPG (view on web)—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
