### ISSUE TITLE
N3 CSV export fails when history is multiple pages

### ISSUE THREAD

**Issue by hal0x2328** [CityOfZion/neon-wallet#2738]
How to reproduce:
1. Log in to an N3 wallet with multiple pages of transactions
2. Go to activity tab
3. Hit the export button
4. See that it never completes - if you look at the network console in developer tools it keeps requesting incrementing empty pages

**Comment by Bazooka2304** [comment]
Thanks for highlighting this

**Comment by thiagocbalducci** [comment]
Hi!

I've attached this to one of our internal issues, we will work on it :)

**Comment by Bazooka2304** [comment]
Hi, any update on this issue or even a workaround? Thanks

**Comment by ixje** [comment]
I've pinged @thiagocbalducci 
Might take until tomorrow to get a response

**Comment by thiagocbalducci** [comment]
Hey guys! Our internal issue is assigned, but we had to resolve some other priority topics before being able to tackle this one.

I will raise its priority and keep this gh issue updated about delivery.

Sorry for the delay!

**Comment by Bazooka2304** [comment]
Thanks for the feedback. Much appreciated

**Comment by Bazooka2304** [comment]
Hi, any update about this?

**Comment by ixje** [comment]
@thiagocbalducci @raulduartep ☝️

**Comment by thiagocbalducci** [comment]
Hi @Bazooka2304 fix is ready. We are testing the next build, aiming at delivering it this week.

**Comment by thiagocbalducci** [comment]
@Bazooka2304 this new version has the fix for this issue: https://github.com/CityOfZion/neon-wallet/releases/tag/v2.24.1

There are still improvements to be made, when there are tons of transactions, the loading communication disappears after a while, but it is still preparing your export, we've expedited this version so that users are at least able to get the file, but we will work on a more general improvement as well.

Sorry it took so long and thank you for your patience.

**Comment by Bazooka2304** [comment]
@thiagocbalducci Thanks for the fix. I'm so happ now :)
