### ISSUE TITLE
NEON wallet

### ISSUE THREAD

**Issue by ioannistsil** [CityOfZion/neon-wallet#2745]
Do i need to migrate NEON wallet versison 2.24.0 or just download version 3.0 ?

**Comment by thiagocbalducci** [comment]
Hi @ioannistsil ! Both options are viable, it depends on whether you want to migrate your accounts and contacts that are already set up on your old Neon to our new wallet.

You can be at ease with this migration as it does not change anything in your usage of our old Neon Wallet, it just creates an enhanced, and safe, export file so that you can more easily port your Neon experience into our new wallet.

After using this process and trying the new one application, you will still be able to use the old wallet app, actually, you can even use both of them at the same time if you so desire :)

**Comment by ioannistsil** [comment]
if i dont have any saved wallet i can skip migration and use NEO 3.01 ?

**Comment by thiagocbalducci** [comment]
Absolutely, you can go ahead and use our new wallet right away, no need to migrate or import anything :)
