### ISSUE TITLE
MY NEO HAS BEEN ROBBED

### ISSUE THREAD

**Issue by Sangacious** [CityOfZion/neon-wallet#387]
## GitHub issues are intended for tracking development tasks, not troubleshooting general usage problems.

Hi,
I am writing to you to inform that I was robbed of my 160 Neo from my Neon Wallet on 1st Dec 2017.

The Thief's Address (the address where my Neo got transferred): AebrfVWTWeYY9WQ9ZYMeyJLMBy4kaTPjSg

I would like you to know if the thief address can be traced. Or if there is in-anyway you can help me to retrieve my Neo. Please let me know.  I will be grateful to you for life!

Thanks.

**Comment by ryanbas21** [comment]
Unfortunately, this isn't a Neon-Wallet issue, but it seems that you lost your private key and someone logged in using it.

**Comment by Colljam** [comment]
It seems that I was also a victim of a theft, the very same NEO wallet receiving my NEO. It is sickening to know that my capital is gone, I lost just 19 NEO, I feel bad for you losing so much more. 

I really thought I had been careful, I set my wallet up offline and had all the necessary precautions in place (at least I thought). I don’t think we will get our NEO back, sorry dude, we were robbed.

**Comment by Sangacious** [comment]
@ryanbas21, no i didn share my private key with anyone. On 1st Dec I  was unable to log on to my wallet. So out of panic I kept logging in to my Neotracker.....  but I dont know when ...dont clearly remember I logged on to the phishing site neotracker.co and thats when i think this all happened.  I am very careful everytime. I have bookmarked neotracker page too .... Anyways I wish Neo had done something to block this phishing site. 

@Colljam  I have lost 160Neo, I have collected in the last three months and thats how I saved my salary but unfortunately only to lose it to a scamster..... this is a huge setback for me !!!! I just regret the biggest mistake of not checking the url ..... biggest fucking mistake!!!! 

Anyways, if in anyway I can retrieve them ( still hoping ) please let me know.

**Comment by Colljam** [comment]
That’s what happened to me too I would guess. I really thought I was being careful. The phishing site still exists... WTF!? Plus it really does look legitimate.... mother fuckers.

**Comment by Sangacious** [comment]
ya the scamster is from Romania ...  imagine the number of people he has scammed ....  and there is no stop to it.... the scma site is soo identical... you would never know the difference...

**Comment by niemc82** [comment]
Where do you download the actual NEON wallet? 
I used this site
https://github.com/CityOfZion/neon-wallet/releases

is this the scammer?

**Comment by Colljam** [comment]
Hey dude, 

That link is legitimate, I believe.  The neon wallet isn’t the issue here, neon is a great wallet. The issue was with the neotracker website that me and the others here used, we should have known better I guess. If you do choose to use the neotracker.io wallet check the address and bookmark it. I believe we used a malicious phishing website neotracker .co (DO NOT USE THIS). Again, Neon wallet is legit and reliable, I use it and I’m happy with its security. 

Hope this helps.

**Comment by cosmic-springs** [comment]
It is EXTREMELY important you record and store your private key somewhere safe, and NEVER reveal it to anyone. Also, always double check the URL of any site you visit via a link to ensure it is authentic, legitimate and the site you intended to visit. Even when being linked from us!
This is from the NEO website. It is the correct url
Yes, Neotraker.io had phishing software last week, 8000 NEO and loads of Nep tokens were sent from other peoples wallets to (AcQZuoHPUCRvdLogJLA3WtGoHBGaM1NzgP) I know because i was one of the people dumb enough to use my private key on neotracker.io, i lost 9 NEO and 2000 DBC :( It just seems so easy for people to take others hard earned money (i don't expect its that easy though) I keep opening my empty wallet...they left me 0.7551 DBC, so that's nice?
Sadly, the wallet hasn't even been shut down yet and its still raking in tokens. Not sure if this is the right place or not to post? I keep getting told to visit neo.org...the site is down. What is going on???

**Comment by cosmic-springs** [comment]
<img width="739" alt="screen shot 2018-02-28 at 9 53 54 pm" src="https://user-images.githubusercontent.com/22673394/36793105-7496283a-1cd7-11e8-919c-7d1f1e596d55.png">

**Comment by cosmic-springs** [comment]
i would say don't use neotracker.io at all until they remove the phishing software?
