### ISSUE TITLE
Getting a "claim failed" error message when trying to claim gas

### ISSUE THREAD

**Issue by cryptocrapitalist** [CityOfZion/neon-wallet#430]
Hi - I am having trouble claiming my gas using the NEON wallet with a WIF. I hit the claim button and it doesn't work. I tried on 3 different versions of the software and multiple times but nothing. "0 NEO" transactions are showing up on the history page, but no GAS ones.  

A couple things to note:
1) I haven't claimed gas in months because I don't like typing in my private key.
2) I got a new Ledger Nano S and set it up last night, and then created a new NEO address/wallet using it.   I have no reason to believe this is causing the problem with my old address, as I've tried claiming the gas on a separate machine,  but figured it may be good to know.   

I'd like to move my NEO to the ledger address but wanted to claim the gas on the old one first.

Thanks

**Comment by cryptocrapitalist** [comment]
I tried all sorts of things with the NEON wallet but couldn't get it to work (removing and sending back NEO and GAS, etc).  Finally I tried the NEO web wallet, and was able to claim the gas on there just fine.

**Comment by pph7** [comment]
Upgrade to 0.0.8. it should work there

**Comment by chewzealand** [comment]
I also have the same issue. 

It's still present in 0.0.9

**Comment by Edgegasm** [comment]
Wanted to weigh in on this because I've had the same issue for a while now.

I've tried claiming GAS with my original NEO address (first one I made from a little while after the ANS rebrand to NEO I think), using both NEON and Neotracker. It doesn't seem to be a NEON-related issue, so if anyone could notify the NEO team about this issue that'd be great.

I've created two new addresses, both of which had no issues claiming GAS. [Here's what Neotracker says when the claim fails.](https://imgur.com/a/sKSl7) It's only my original NEO address that can't claim GAS, which leads me to believe this issue might be linked to older NEO addresses.

**Comment by cryptocrapitalist** [comment]
Yes- I ended up using the web wallet to claim and then shifted everything to the new ledger address.

**Comment by sunondeck** [comment]
I think you're right Edgegasm - it could be to do with older addresses. 

Mine was an old ANS address and I'd never attempted to claim GAS until just now. 

I couldn't get the NEON wallet to work at all. 

In the end I downloaded the original neo-gui.exe wallet and waited (a long time) for the blockchain to fully sync. I was then able to claim the GAS using that. 

Interestingly, once I'd made that initial claim using the neo-gui.exe wallet I was then able to successfully claim subsequent GAS using the NEON wallet.

**Comment by jayddaniels** [comment]
I have the same issue, i try to claim my gas with neon wallet 0.0.9 and is immediatly says  "error claim failed" there is no 5 minute halt before being able to claim, i can claim infinite times and it says error infinite times. please help.

**Comment by anfn101** [comment]
Try latest version 0.1.2
