### ISSUE TITLE
NEON 0.0.9 and scripthashes

### ISSUE THREAD

**Issue by seaside-crypto** [CityOfZion/neon-wallet#518]
Hey CoZ,

with all the upcoming ICOs i noticed, that it is, in fact, very important to add the scripthash feature to NEON 0.0.9.

Many people registered and whitelisted for these ICOs with their ledger address just to find out that they cant use this address for the ICO because they cant invoke the smart contract.

**Comment by Sajjon** [comment]
👍 

Why was script hash function removed in 0.0.7 and when will it get re-added? :)

**Comment by brianlenz** [comment]
We are in the same boat. We are running an ICO on NEO and will need contributors to contribute via the `mintTokens` smart contract function. Without support for this, we'd have to handle all contributions manually through a separate NEO wallet. It's much preferable to have a smart contract handle the contributions so that it can enforce rules like whitelisting, contribution limits, etc.

Any updates, CoZ?

**Comment by seaside-crypto** [comment]
Scripthash function has been implemented with NEON 0.1.1. Issue can be closed.
