### ISSUE TITLE
problem claiming gas, sending/receiving neo, sending/receiving RPX

### ISSUE THREAD

**Issue by royale44** [CityOfZion/neon-wallet#624]
I'm using the Neon wallet 0.1.1 and when I try to claim gas or send neo, it comes back as transaction failed.. anyone else having this problem? it is currently 1/30/2018 @ 2:38am KST.

**Comment by curatedcryptocurrencynews** [comment]
same issue: https://github.com/CityOfZion/neon-wallet/issues/621

**Comment by curatedcryptocurrencynews** [comment]
I am now also able to claim GAS. Issue seems to be fully resolved for me.

**Comment by sgehrman** [comment]
same issue

**Comment by IraBerenhaus** [comment]
This is very scary that City of Zion provides a NEON wallet that doesn't work properly.  What does that say about their quality control process.  It's easy enough to check that every aspect of a wallet works including claiming GAS.  I'm having the same problem as everyone else and there are many people Reddit expressing the same issues with NEON Wallet 0.1.1

**Comment by sgehrman** [comment]
The code should be rewritten. It's a mess and obviously not fixable since problems keep coming up. Is there a viable alternative to switch to?

**Comment by stevesbrain** [comment]
@sgehrman As far as I know, there's no other lightweight wallet/solution available at this time.

**Comment by stevesbrain** [comment]
@IraBerenhaus I don't believe it's an issue with the code - claiming, sending, etc all works. I think the issue is network related - either for those behind filters/proxies, or, perhaps the CoZ servers themselves at times experiencing connectivity/load issues.

**Comment by JoeyVV** [comment]
Hi guys, I'm also having problems with withdrawal my RPX to exchange. It seems to be working until i push the button to send my RPX. i get error directly after sending  'Transaction failed'.
My balance showing the RPX but can't withdrawal.
Is this a Ledger problem or Neon wallet 1.2.1 problem?
and are the tokens lost or only no withdrawal?

And of course what to do? Nobody seems to know an solution... 

Greetings Joey.

**Comment by JoeyVV** [comment]
PS: Tried several wallets before!

**Comment by IraBerenhaus** [comment]
Alan,

 

It’s very nice that you closed this case, but is the problem solved?  It would be good to leave a comment explaining that the problem is resolved and what was done to resolve it.  Perhaps you issued has been resolved because you issued a new NEON wallet 0.1.2.  Perhaps the issue is solved because it’s a browser issue – although using Ledger, we can only use Chrome.  Perhaps the issue is solved because it was an intermittent server issue.

 

OR

 

Perhaps the issue has not been solved.

 

Some explanation would be helpful.

 

I’ll try the new wallet and post the results.

 

If you have an explanation, please reply to this email or post it on GitHub.

 

Thanks,

 

Ira

 

Ira Berenhaus

37 Jamie Court, 2nd floor

Bloomfield, NJ  07003

(973) 566-0095 (home)

(866) 522-5889 (fax)

(973) 495-9411 (cell)

iberenhaus@gmail.com <mailto:iberenhaus@gmail.com>  (e-mail)

**Comment by anfn101** [comment]
Duplicate question (see #662)
