### ISSUE TITLE
Lost/stolen NEO?

### ISSUE THREAD

**Issue by cosmic-springs** [CityOfZion/neon-wallet#680]
I have now lost 9 NEO and around 2000 DBC. They disappeared from my wallet and the NEO are showing in my transaction history (-9). However, no transaction was made by me?? It’s everything i had :(
Hash: 49774c05a3c7a7d9e90912f168e834077988f58f806441469f04bca0ffa3021c
Time: 07/02/2018, 17:17:19
Wallet: AU6GkGRt4jeESJnM56mz9uJiwacNMTHjzH

Have I been Hacked/Phished?
Is this just part of the mysterious disappearing and often reappearing of NEO from various wallets and ledgers (I lost one around a month ago but reappeared a week later)?
Is there any place ‘safe’ to store NEO?
Any assistance/advice/HELP! Would be greatly appreciated.

**Comment by stevesbrain** [comment]
That transaction shows your 9 NEO being transferred to an address that was created less than 24 hours beforehand. That address has a lot of balance of a bunch of tokens. This isn't one of your exchange addresses is it?

**Comment by cosmic-springs** [comment]
Sadly, its not my address/wallet, if it was i wouldn't be too bothered about 9 NEO. Yes i did log into neotracker.io (the correct link) because transfers from Kucoin haven't gone through after 3 days and i needed to check.
I am confident now that it's been nicked. My crypto days are over until it becomes a system with even basic security. There are too many dodgy things going on, not just hackers/phishers but even the exchanges are being dodgy now (especially Kucoin) I appreciate you checking it out though, best part of this whole debacle is the support and efforts of the people on these sites. 
Strange thing is that i lost 1 NEO a few weeks back, it was in a wallet with a large number of NEO coins (not my own) It then mysteriously appeared back in my wallet??
I cant help thinking the whole thing is dodgy?

**Comment by cosmic-springs** [comment]
No sign of the 1800 DBC coins but they are missing too.

**Comment by stevesbrain** [comment]
@cosmic-springs I can understand you wanting to pull out; that's fair. However, it's not so much an issue with the security of the protocol/coin (which is solid), but rather the fact that it's a high-target/high-risk area. I.e. because the money is easier to steal due to not having to leave your seat + the irreversible nature of a transaction once made. 

The issue of losing your coins usually boils down to:

- Insufficient care taken to protect private key
- Insufficient care taken to protect yourself from phishing
- Exchange being dodgy
- Targeted attack

Not at all trying to blame you - just wanted to make sure you weren't falsely thinking it was a broken protocol/concept. Certainly a high risk investment though. I wish you better luck with future investments (both here, and in the "real world").

**Comment by cosmic-springs** [comment]
You are absolutely right about all of the above @stevesbrain i hadn't had breakfast and i was pissed, we live and learn, I will definitely check the exchange idea though, Thanks ;)

**Comment by stevesbrain** [comment]
No worries at all @cosmic-springs - hope your day improves :)

**Comment by totalvm** [comment]
Sorry for your loss, I'll be closing the issue as it has nothing to do with the wallet itself
