### ISSUE TITLE
Trying to install Neon wallet 0.1.3

### ISSUE THREAD

**Issue by hd3htown** [CityOfZion/neon-wallet#719]
When the install bar comes up it fails and says I dont have a program installed for dealing with this request.. my other wallet was working fine why did i press update ffs now i have none !

**Comment by jagjjb** [comment]
Having continual issues installing Neon wallet with my Mac using nano-s.  Has to be a configuration issue since this is the 2nd device from Ledger not working. It keeps showing- Device Error and Unable to Install. I cannot figure this out. Help!
![img_8933](https://user-images.githubusercontent.com/34401318/36331966-1c106a10-133e-11e8-9e53-6a58e05ab393.jpeg)
![img_8932](https://user-images.githubusercontent.com/34401318/36331975-29440886-133e-11e8-92e5-fc80f435c21b.jpeg)

**Comment by mhuggins** [comment]
Please try downloading the latest version, a number of issues have been addressed.
