### ISSUE TITLE
Transaction from Nano Ledger to Kucoin

### ISSUE THREAD

**Issue by Tristan1986** [CityOfZion/neon-wallet#907]
Hi there,

When I check Neotracker i see the ''something went wrong message''. For about one hour ago I did this transfer: https://neotracker.io/tx/2f3f6df41cc267072cfdbd8a7e1f1b995a49ac45d0f56f9629c330c3139db488

Send from Nano Ledger to Kucoin ZPT adress. I still do not have the coins in my Kucoin wallet.  Does someone know what could have happened?

Thanks!

**Comment by mhuggins** [comment]
Neotracker may be having issues.  Your transaction shows on Neoscan: https://neoscan.io/transaction/2f3f6df41cc267072cfdbd8a7e1f1b995a49ac45d0f56f9629c330c3139db488

Since your transaction is showing on the blockchain, if Kucoin doesn't show your updated balance, then you will need to communicate with them.
